add exception handling programs
computerclubkec/oop pull request #24
Opened 2023-10-27 16:23 UTC by aayush105

2023-10-27 16:34 UTC, gaurovgiri requested changes

2023-10-27 16:34 UTC, gaurovgiri commented on programs/ExceptionHandling/q1.cpp
Use a simple case like when negative throw error and catch the negative number then display it.

2023-10-27 16:34 UTC, gaurovgiri commented on programs/ExceptionHandling/q10.cpp
Need another example with more simple and complete code.

2023-10-27 16:34 UTC, gaurovgiri commented on programs/ExceptionHandling/q4.cpp
Take two numbers and divide them, if the denominator is 0 throw or if any number is negative throw exception.

2023-10-27 16:34 UTC, gaurovgiri commented on programs/ExceptionHandling/q7.cpp
> +{
add a constructor so that, it can handle the exception from inside.

2023-10-27 16:35 UTC, nawarajshah approved these changes

2023-10-28 16:45 UTC, gaurovgiri approved these changes
LGTM!

2023-10-28 16:46 UTC, merged