cpp-language-construct-add
computerclubkec/oop pull request #4
Opened 2023-10-14 18:47 UTC by aayush105

2023-10-15 10:27 UTC, gaurovgiri requested changes

2023-10-15 10:27 UTC, thegauravgiri commented on CppLanguageConstructs/q12.cpp
Another simple code for this question as there is already a swapping question.

2023-10-15 10:27 UTC, thegauravgiri commented on CppLanguageConstructs/q16.cpp
Delete this.

2023-10-15 10:27 UTC, gaurovgiri commented on CppLanguageConstructs/q5.cpp
> +    return 3.14 * radius * radius;
use #define macro for 3.14 set it to PI

2023-10-15 16:20 UTC, aayush105 commented on CppLanguageConstructs/q12.cpp
ok got it

2023-10-15 16:20 UTC, aayush105 commented on CppLanguageConstructs/q16.cpp
sureee

2023-10-15 16:20 UTC, aayush105 commented on CppLanguageConstructs/q5.cpp
> +    return 3.14 * radius * radius;
okay suree

2023-10-15 18:42 UTC, aayush105 commented
Check it bro @gaurovgiri ,Ii have updated the solution of the problem that you had mentioned.

2023-10-16 09:40 UTC, gaurovgiri approved these changes
LGTM

2023-10-16 09:40 UTC, merged